/*
 * IConfiguration and IOption test
 *
 * Test API to show using IOptions and IConfiguration
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: myemail@bogus.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using IOptionTest.Models;
using IOptionTest.Attributes;

namespace IOptionTest.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class LoggerApiController : ControllerBase
    {
        private readonly ILogger<LoggerApiController> _logger;
        static string EyeCatcher = "OOOOOOOOOOOOOOOOOOO";

        public LoggerApiController(ILogger<LoggerApiController> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Log a message
        /// </summary>
        /// <param name="message">Message to log</param>
        /// <response code="200">Ok</response>
        /// <response code="400">bad input parameter</response>
        [HttpPost]
        [Route("/api/logger")]
        [ValidateModelState]
        [SwaggerOperation("LogMessage")]
        public virtual IActionResult LogMessage([FromBody]Message message)
        {
            _logger.Log(message.Level, "{eyeCatcher} Logging with {level} and message {message}",
                                            EyeCatcher, message.Level, message._Message);
            return Ok();
        }
    }
}
